### ISSUE TITLE
choose* ing from list of unknown length

### ISSUE THREAD

**Issue by freemin7** [emina/rosette#270] opened 2023-11-01 13:42 UTC
I want to build a program in SSA form and angelic execution. I want to make sure it is SSA by manually maintaining a list what variables can be selected at a particular point in time, which depends on previous choices.

However i fail to make that work even in a simple case:
```
#lang rosette/safe

(require rosette/lib/synthax rosette/solver/smt/boolector rosette/solver/smt/z3)
(require rosette/lib/angelic racket/list)

(current-bitwidth #f)
(define-symbolic y integer?)

(solve (begin (assert (eq? 16 y))
            (assert (eq? 12  (apply choose* (range y  ))))
            ))


(synthesize #:forall (list) #:guarantee
            (assert (eq? 12  (apply choose* (range y )))))
```
I tried several solver combinations with no success. Using choose results in a bad syntax error. From the documentation it is not clear whether the n in the description must not depend on a variable. I see no good justification why it is impossible in principle to do this.

**Comment by sorawee** [comment] 2023-11-01 13:57
The issue is with `(range y)`, as `range` is not lifted (i.e., it doesn't appear as a supported operation in [this page](https://docs.racket-lang.org/rosette-guide/sec_pair.html)). Our [symbolic error tracer](https://docs.racket-lang.org/rosette-guide/ch_error-tracing.html#%28part._sec~3aerror-tracer%29) could be used to reveal the problem in your program.

Fundamentally, even if `(range y)` doesn't error, it would instead loop infinitely, because `range` works by recursively constructing elements, but since `y` is a symbolic value, this recursion will only create more symbolic values, with no termination. We explained this phenomenon in [this section](https://docs.racket-lang.org/rosette-guide/ch_essentials.html#%28part._.Symbolic_.Evaluation%29).

Instead, you can do something like this.

```
#lang rosette

(define-symbolic y x integer?)

(solve
 (begin
   (assert (eq? 16 y))
   (assert (eq? 12 x))
   (assert (<= 0 x (sub1 y)))))
```

**Comment by sorawee** [comment] 2023-12-07 02:55
Let me close this now, but if you have any follow-up question, feel free to reach out.

**Closed by sorawee** 2023-12-07 02:55 UTC
