### ISSUE TITLE
(if ...) emits assertions in situations where it might be easily avoided

### ISSUE THREAD

**Issue by anishathalye** [emina/rosette#164] opened 2020-06-18 21:24 UTC
I wasn't quite sure how to title the issue -- I don't know what exactly the spec should be for when `if` should produce assertions, but not emitting assertions in simple pure functional programs that are free of type errors etc. seemed like one desirable behavior.

Here's a concrete program that doesn't behave the way I would expect:

```racket
#lang rosette/safe

(define-symbolic* a1 a2 boolean?)

(asserts)
; => '()

(if a1
    (if a2
        0
        (if (&& a1 a2)
            1
            2))
    3)
; => (ite a1 (ite a2 0 2) 3)

(asserts)
; => (list (|| (! (&& a1 a2)) (! (&& a1 (! a2)))))
```

I would have expected the assertion list to be false (Rosette figured out that the true branch of the third `if` is infeasible, so why add the negation to the assertion store?). Alternatively, I would have been okay if Rosette hadn't been able to figure out that the true branch of the third `if` is unreachable and produced:

```
(ite a1 (ite a2 0 (ite (&& a1 a2) 1 2)) 3)
```

(again, with an empty assertion store)

Here's my understanding of what's going on:

`if`, if condition is not `eq?` to `#t` or `#f`, calls speculate to try both the true and false branches, using `test` / `(! test)` as the guards. `speculate` parameterizes the pc with guard. The parameter `pc` has a guard procedure that sets the pc to `(&& (pc) new-pc)`, raises an exception if it's `#f`. Back in `if`, if speculation on either branch fails, the code adds an appropriate assertion for `test` or `(! test)`, which adds `(=> (pc) guard)` to the assertion store.

It's a bit unfortunate if `(&& (pc) test)` evaluates to `#f` in Racket, but `(=> (pc) (! test))` does not, resulting in the situation described above. Here is a more self-contained demo:

```racket
#lang rosette/safe

(define-symbolic* a1 a2 boolean?)

(define $pc
  (&& a1 (! a2)))

(define $test
  (&& a1 a2))

(&& $pc $test)
; => #f

(=> $pc (! $test))
; => (|| (! (&& a1 a2)) (! (&& a1 (! a2))))
```

It could be neat if you could have a guarantee that if `(&& (pc) test)` evaluates to a constant `#f` in Racket, then nothing is added to the assertion store. I can think of a couple ideas for how this behavior could be fixed but I'm not sure what is the right fix.

- It would be neat if there was a guarantee relating the rewrite/simplification for `&&` and `=>`, so that if `(&& a b)` evaluates to `#f` in Racket, then `(=> a (! b))` is guaranteed to evaluate to `#t`. I haven't looked way too deeply into the simplification rules, so I don't know how hard this would be to do in a natural way. (A hacky way to trivially have this property might be with something like `(define (=> a b) (if (eq? #f (&& a (! b))) #t {fallback}))`, though I'm not proposing this as an actual fix)
- Perhaps `if` / `branch-and-merge` could check for the situation where `(&& (pc) test)` or `(&& (pc) (! test))` evaluates to `#f` in Racket, and in that case, not bother with polluting the assertion store.

---

Is this behavior considered a bug? If so, I'd be happy to try to contribute a fix if you can point me in the right direction.

(Also, if not, do you have any suggestions for working around this behavior?)

**Comment by emina** [comment] 2020-06-18 22:53
This behavior is correct.  Rosette guarantees that its global state is sound (modulo bugs in the implementation, of course), when you take into account the combination of the program store (i.e., the values of all program variables), the path condition, and the assertion store.

Redundant assertions are okay---i.e., not a bug---and in general, unavoidable.  Basically, at the point the assertion is generated, we can't tell that a program is and will remain fully functional, so generating such assertions is necessary to ensure soundness in all cases.

This particular redundancy could in theory be caught by the Rosette rewriter, but, of course, any set of rewrite rules implemented in a system like Rosette will be incomplete.  In this case, Rosette doesn't have a rule to decide that `(|| (! (&& a1 a2)) (! (&& a1 (! a2))))` is always `#t`. 

These redundant assertions are not a problem in our experience (in terms of performance), but if if they are in your case, you can write a loop that verifies the generated assertions one at a time, and throws out the UNSAT ones. 

Note though that @xiw found that verifying assertions one by one was slower than checking them simultaneously, as Rosette does by default, at least for the kinds of programs Serval verifies.

**Closed by emina** 2020-06-18 22:53 UTC

**Comment by anishathalye** [comment] 2020-06-18 23:13
Thanks for the response -- that makes sense, I'll try a workaround (in my particular case, the assertion store becomes really large and slows things down).

(I wasn't expecting Rosette's rewrites to be complete. More that I wanted `&&` to be "just as powerful" as `=>`, that if one produces a concrete value in Racket, then the other should too.)
